import 'package:test/test.dart';

import 'narrative_generator_test.dart' as narrative_fixture;

void main() {
  group('Architecture risks and observations', () {
    test('generates deterministic risks markdown', () {
      final narrative = narrative_fixture.buildNarrativeFixture();

      expect(
        narrative.risksMarkdown.trim(),
        '''
<!-- GENERATED FILE - DO NOT EDIT MANUALLY -->
# Architecture Findings

Findings are grouped by severity. Observations are non-failing unless promoted by `risk_rules`.

## Errors

| Severity | Code | Subject | Message | Remediation |
| --- | --- | --- | --- | --- |
| Error | `API001` | pkg_impl | is missing public entrypoint `lib/pkg_impl.dart`. | [How to fix](../remediation.md#api001-missing-public-entrypoint) |

## Warnings

| Severity | Code | Subject | Message | Remediation |
| --- | --- | --- | --- | --- |
| Warning | `API003` | pkg_core | has 1 internal public declarations. | [How to fix](../remediation.md#api003-internal-public-declarations) |
| Warning | `COMP001` | Impl Component | has unknown responsibility. | [How to fix](../remediation.md#comp001-unknown-responsibility) |
| Warning | `COMP002` | Impl Component | has no public API. | [How to fix](../remediation.md#comp002-component-without-public-api) |

## Observations

| Severity | Code | Subject | Message | Remediation |
| --- | --- | --- | --- | --- |
| Observation | `COMP003` | Impl Component | has no dependents. | [How to fix](../remediation.md#comp003-component-without-dependents) |
| Observation | `COMP004` | Core Component | has no dependencies. | [How to fix](../remediation.md#comp004-component-without-dependencies) |

## OK / Healthy Signals

None detected.

## Validation Policy

The findings above are documentation-oriented. `validate` reports findings generated by active rules in `arch_doc.yaml` and can promote configured severities to errors.

| Policy | Value |
| --- | --- |
| `fail_on_risks` | `false` |
| `fail_on_warnings` | `false` |
| `fail_on_observations` | `false` |
'''
            .trim(),
      );
    });
  });
}
